FROM python:alpine

RUN adduser -D sdsnap
WORKDIR /home/sdsnap

COPY --chown=sdsnap:sdsnap package .
RUN apk --no-cache add libxml2-dev libxslt-dev gcc libc-dev && python -m venv venv \
  && venv/bin/pip install -r requirements.txt && venv/bin/pip install gunicorn \
  && chmod +x boot.sh

ENV FLASK_APP flask-snap.py
ENV FLASK_ENV development
ENV FLASK_RUN_PORT 5050
USER sdsnap

EXPOSE 5050
ENTRYPOINT ["./boot.sh"]
