name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  DeployImage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kube
      uses: actions/checkout@v2
    - name: Login to dockerhub
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile.alpine --tag ${{ secrets.DOCKER_USERNAME }}/flask-sdsnap:$(date +%s)
      working-directory: apps/flask-snap
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-sdsnap
    - name: Cleanup
      run: docker logout
